# attestation-policy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: attestation-policy
  namespace: trustee-operator-system
data:
  default.rego: |
    package policy

    import rego.v1

    # This policy validates multiple TEE platforms
    # The policy is meant to capture the TCB requirements
    # for confidential containers.

    # This policy is used to generate an EAR Appraisal.
    # Specifically it generates an AR4SI result.
    # More informatino on AR4SI can be found at
    # <https://datatracker.ietf.org/doc/draft-ietf-rats-ar4si/>

    # For the `executables` trust claim, the value 33 stands for
    # "Runtime memory includes executables, scripts, files, and/or
    #  objects which are not recognized."
    default executables := 33

    # For the `hardware` trust claim, the value 97 stands for
    # "A Verifier does not recognize an Attester's hardware or
    #  firmware, but it should be recognized."
    default hardware := 97

    # For the `configuration` trust claim the value 36 stands for
    # "Elements of the configuration relevant to security are
    #  unavailable to the Verifier."
    default configuration := 36



    ##### SNP
    executables := 3 if {
      # In the future, we might calculate this measurement here various components
      input.snp.measurement in data.reference.measurement
    }

    hardware := 2 if {
      # Check the reported TCB to validate the ASP FW
      input.snp.reported_tcb_bootloader in data.reference.tcb_bootloader
      input.snp.reported_tcb_microcode in data.reference.tcb_microcode
      input.snp.reported_tcb_snp in data.reference.tcb_snp
      input.snp.reported_tcb_tee in data.reference.tcb_tee
    }

    # For the 'configuration' trust claim 2 stands for
    # "The configuration is a known and approved config."
    #
    # For this, we compare all the configuration fields.
    #configuration := 2 if {
    #  input.snp.policy_debug_allowed == 0
    #  input.snp.policy_migrate_ma == 0
    #  input.snp.platform_smt_enabled in data.reference.smt_enabled
    #  input.snp.platform_tsme_enabled in data.reference.tsme_enabled
    #  input.snp.policy_abi_major in data.reference.abi_major
    #  input.snp.policy_abi_minor in data.reference.abi_minor
    #  input.snp.policy_single_socket in data.reference.single_socket
    #  input.snp.policy_smt_allowed in data.reference.smt_allowed
    #}
