# trustee-resource-policy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: trustee-operator-system
data:
  policy.rego: |
    package policy
    import rego.v1

    default allow = false
    allow if {
      input["submods"]["cpu"]["ear.status"] != "contraindicated"
      input["submods"]["cpu"]["ear.trustworthiness-vector"]["config"] == 2
      input["submods"]["cpu"]["ear.trustworthiness-vector"]["hardware"] == 2
      input["submods"]["cpu"]["ear.trustworthiness-vector"]["executables"] == 3
    }
